### ISSUE TITLE
Fatal Exception - EGLConfigChooser (eglGetConfigAttrib) - EGLImpl

### ISSUE THREAD

**Issue by PetkevichPavel** [mapbox/mapbox-gl-native-android#435]
Hello, our application is crashed on this error:
```stacktrace
Fatal Exception: java.lang.IllegalArgumentException
       at com.google.android.gles_jni.EGLImpl.eglGetConfigAttrib(EGLImpl.java)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.a(EGLConfigChooser.java:3)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.a(EGLConfigChooser.java:25)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(EGLConfigChooser.java:20)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1053)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1429)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

As I found you previously faced with that kind of problem in 2019, and it was because of the </br> `config == null` [issue 374](https://github.com/mapbox/mapbox-gl-native-android/issues/374).

Mapbox libs which I used in the project:
• core - com.mapbox.mapboxsdk:mapbox-android-sdk:<b>9.1.0</b>
• services - com.mapbox.mapboxsdk:mapbox-sdk-services:<b>5.2.1</b>
• anatationsPlugin - com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-<b>v9:0.8.0</b>

**Comment by Chaoba** [comment]
The exception oriented from method `eglGetConfigAttrib`, so it is the same with #374. 
Close this as it is resolved.

**Comment by rajeshp2511** [comment]
@Chaoba Still happening for me on Device LG K8(2018) , OS : 8.1.0.

Here is stacktrace for crash : 

> Fatal Exception: java.lang.IllegalArgumentException
       at com.google.android.gles_jni.EGLImpl.eglGetConfigAttrib(EGLImpl.java)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.getConfigAttr(EGLConfigChooser.java:3)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseBestMatchConfig(EGLConfigChooser.java:25)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(EGLConfigChooser.java:20)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1053)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1429)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

Mapbox libs which I used in the project:
- core - com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.1
- services - 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.7.0
- place  - 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v8:0.9.0'
- traffic plugin-  'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic-v8:0.9.0'
- markerview 'com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v8:0.3.0'

**Comment by Chaoba** [comment]
@rajeshp2511 I don't think 9.2.1 contains this fix, can you try to update to the lastest version?

**Comment by rajeshp2511** [comment]
@Chaoba 9.5.2 fix the issue, Thanks for help
